-- Write your UP migration SQL here

-- Update the symbols table to add all missing columns
-- First ensure the name column is NOT NULL
ALTER TABLE symbols ALTER COLUMN name SET NOT NULL;

-- Add all missing columns from the full schema
ALTER TABLE symbols
    ADD COLUMN IF NOT EXISTS exchange_id VARCHAR(30),
    ADD COLUMN IF NOT EXISTS segment VARCHAR(10),
    ADD COLUMN IF NOT EXISTS security_id VARCHAR(30),
    ADD COLUMN IF NOT EXISTS isin VARCHAR(20),
    ADD COLUMN IF NOT EXISTS instrument VARCHAR(30),
    ADD COLUMN IF NOT EXISTS underlying_security_id VARCHAR(30),
    ADD COLUMN IF NOT EXISTS underlying_symbol VARCHAR(30),
    ADD COLUMN IF NOT EXISTS symbol_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS instrument_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS series VARCHAR(10),
    ADD COLUMN IF NOT EXISTS lot_size DECIMAL(10, 1),
    ADD COLUMN IF NOT EXISTS expiry_date VARCHAR(30),
    ADD COLUMN IF NOT EXISTS strike_price DECIMAL(10, 5),
    ADD COLUMN IF NOT EXISTS option_type VARCHAR(10),
    ADD COLUMN IF NOT EXISTS tick_size DECIMAL(10, 4),
    ADD COLUMN IF NOT EXISTS expiry_flag VARCHAR(5),
    ADD COLUMN IF NOT EXISTS bracket_flag CHAR(1),
    ADD COLUMN IF NOT EXISTS cover_flag CHAR(1),
    ADD COLUMN IF NOT EXISTS asm_gsm_flag CHAR(1),
    ADD COLUMN IF NOT EXISTS asm_gsm_category VARCHAR(10),
    ADD COLUMN IF NOT EXISTS buy_sell_indicator CHAR(1),
    ADD COLUMN IF NOT EXISTS buy_co_min_margin_per DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_co_min_margin_per DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_co_sl_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_co_sl_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_co_sl_range_min_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_co_sl_range_min_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_bo_min_margin_per DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_bo_min_margin_per DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_bo_sl_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_bo_sl_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_bo_sl_range_min_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_bo_min_range DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_bo_profit_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_bo_profit_range_max_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS buy_bo_profit_range_min_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS sell_bo_profit_range_min_perc DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS mtf_leverage DECIMAL(10, 2),
    ADD COLUMN IF NOT EXISTS custom_symbol VARCHAR(50),
    ADD COLUMN IF NOT EXISTS expiry_code VARCHAR(10),
    ADD COLUMN IF NOT EXISTS trading_symbol VARCHAR(50),
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();
